# Disable "Missing top-level module documentation comment."
Documentation:
  Enabled: false

# Disable "Use nested module/class definitions instead of compact style."
ClassAndModuleChildren:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'  

# Override linelength. Sometimes u need to break the 80chars rule..
Metrics/LineLength:
  Max: 150