development:
  adapter: postgresql
  database: howhard
  pool: 5
  timeout: 5000
  encoding: unicode

test:
  adapter: postgresql
  host: localhost
  database: howhard_test
  pool: 5
  timeout: 5000
  encoding: unicode
